### ISSUE TITLE
Benchmarking

### ISSUE THREAD

**Issue by ml31415** [nschloe/fastfunc#18]
Hi @nschloe ,
one remark about the benchmarks. As the author of the `numpy_groupies` package, I'm a bit surprised, that our implementation performed even worse than `np.bincount` in your benchmarking. Do you actually have `numba` installed on your machine? If it's not available, we use a pure numpy implementation as a fallback solution, i.e. our `sum` just does `np.bincount` itself. The numba version is a fair bit faster.

**Comment by nschloe** [comment]
Interesting, didn't know this. I wasn't able to install numba on my machine, so I've simply removed numpy_groupies from the plot. Thanks again for letting me know!
