### ISSUE TITLE
Compilation issues: add more details about troubleshooting 

### ISSUE THREAD

**Issue by kayarre** [nschloe/fastfunc#8]
using a conda environment  with python 3.X
```
pip install fastfunc
```
fails with
```
error: command 'gcc' failed with exit status 1
```
I believe it may have to do with the version of gcc (here I am using gcc 5.5.0) being used or the compilation flags (not sure if -std=c++11 is the culprit)

Can you provide insight about gcc version being used / environment / etc that might help determining the issue?

**Comment by nschloe** [comment]
> Can you provide insight about gcc version being used / environment / etc that might help determining the issue?

GCC 5 is pretty ancient indeed, so I'm not surprised that the compilations fails. I myself use GCC 7 or later.

**Comment by kayarre** [comment]
Easiest path is to indicate this information somewhere I suppose. I will test with updated gcc.

**Comment by copono** [comment]
I was having the same problem with the default compiler on mac, so I installed gcc using brew. Unfortunately this doesn't solve the problem and I get the following error
`clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9 [-Wdeprecated]
  ld: library not found for -lstdc++
  clang: error: linker command failed with exit code 1 (use -v to see invocation)
`

**Comment by copono** [comment]
I fixed it replacing adding a few options to the Extension. Here's what I got. 
```
if platform.system() == "Darwin":
    #compile_extra_args = ['-std=c++11', "-mmacosx-version-min=10.9"]
    link_extra_args = ["-stdlib=libc++", "-mmacosx-version-min=10.9"]
else:
    link_extra_args = []

ext_modules = [
    Extension(
        "_fastfunc",
        ["src/pybind11.cpp"],
        language="c++",
        include_dirs=[
            # '/usr/include/eigen3/',
            # Path to pybind11 headers
            get_pybind_include(),
            get_pybind_include(user=True),
        ],
        libraries=[],
        # -std=c++11 is needed for older compilers (see, e.g.,
        # <https://github.com/nschloe/optimesh/issues/26>)
        extra_compile_args=["-std=c++11"],
        extra_link_args=link_extra_args,
    )
]
```

**Comment by copono** [comment]
Actually this causes problems that I don't quite understand and I get a `Symbol not found` error.

**Comment by nschloe** [comment]
I've updated `setup.py` according to the pybind11 recommendations (https://github.com/pybind/python_example/blob/master/setup.py) to hopefully fix some of the issues here. Could you try it out?

**Comment by copono** [comment]
That was so fast! Thank you very much. Unfortunately I'm still having that problem. I see a `Symbol not found` error. It also says `Expected in: flat namespace`.
I don't know if I did something wrong when installing or something. I used `pip install -e .`

**Comment by nschloe** [comment]
You're on MacOS, right? I'm on Linux myself, so I'd have to rely on you to provide the _full_ error message.

**Comment by nschloe** [comment]
And first of all, you should be using Python 3 (`pip3 install`).

**Comment by copono** [comment]
Sure. It's
```
Traceback (most recent call last):
  File "<myfile1>", line 9, in <module>
    from pyfem import <mythings>
  File "<myfile2>", line 42, in <module>
    import fastfunc
  File "<mydir>/fastfunc/__init__.py", line 15, in <module>
    from . import add, subtract, multiply, divide
  File "<mydir>/fastfunc/add.py", line 3, in <module>
    from _fastfunc import _add_at
ImportError: dlopen(<mydir>/fastfunc/_fastfunc.cpython-36m-darwin.so, 2): Symbol not found: __ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE4findEPKcmm
  Referenced from: <mydir>/fastfunc/_fastfunc.cpython-36m-darwin.so
  Expected in: flat namespace
 in <mydir>/fastfunc/_fastfunc.cpython-36m-darwin.so
```
I censored the directories and my file names using <my...>.

That pip comes from conda. `pip --version` shows:
`pip 19.0.3 from  <mydir>/anaconda3/envs/<myenv>/lib/python3.6/site-packages/pip (python 3.6)`

**Comment by copono** [comment]
If you have a minimal example or something that you would like me to run, please let me know.

**Comment by nschloe** [comment]
If something as basic as `basic_string` isn't found, it's probably a MacOS quirk. Looks like [this error](https://stackoverflow.com/a/51156617/353337). Some resources recommend switching the compiler to clang++.

**Comment by kayarre** [comment]
This has been resolved on my local linux machine. not really sure what the culprit was but I was able to build without issue.

**Comment by nschloe** [comment]
Alright, closing.
